version: '3.2'

services:
  db:
    image: postgres:12.3-alpine
    env_file:
      - ./envs/docker.dev
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - postgres:/data/postgres
    ports:
      - 5432:5432

  app:
    image: bestlibre/shhh
    depends_on:
      - db
    env_file:
      - ./envs/docker.dev
    ports:
      - 5000:5000

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres:
