version: "2.1"
services:
  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/emby/config:/config
      - ./data/media/tvshows:/data/tvshows
      - ./data/media/movies:/data/movies
      - ./data/transcoding:/transcode #optional
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8082:8096
    devices:
      - /dev/vchiq:/dev/vchiq #optional
    restart: unless-stopped
