version: '3'

services:
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - internal_network
    volumes:
      - ./data/maria_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_PASSWORD=secretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - internal_network
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./data/nextcloud/www:/var/www/html
      - ./data/nextcloud/config:/var/www/html/config
      - ./data/nextcloud/custom_apps:/var/www/html/custom_apps
      - ./data/nextcloud/data:/var/www/html/data
      - ./data/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secretpassword
      - MYSQL_HOST=localhost
    restart: unless-stopped

networks:
  internal_network:
