version: "3"
services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
      - ./data:/mnt2:z
    command: '-s "mnt;/mnt;yes;no;no;jimmy;jimmy;jimmy" -s "Pirate Box;/mnt2;yes;no;no;jimmy;jimmy" -u "jimmy;jimmy" -w "DEFAULT" -p'

networks:
  default:
